name: Run Graft Compatibility

on:
  push:
    branches: [ main ]  # Runs on push to main
  workflow_dispatch:    # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Grabs your repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Matches your local setup

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas flask  # Add any other libs if needed

      - name: Run the script
        run: python main.py

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: compatibility-results
          path: graft_compatibility_results.csv  # Saves CSV as artifact
